import { MetadataRoute } from 'next'

type SitemapEntry = {
  path: string
  changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency']
  priority: number
}

const baseUrl = 'https://pileperde.com.tr'

const sitemapEntries: SitemapEntry[] = [
  { path: '/', changeFrequency: 'yearly', priority: 1 },
  { path: '/hakkimizda', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/iletisim', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/kurumsal', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/urunler', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/urunler/mekanizmali-perdeler', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/urunler/mekanizmali-perdeler/jaluzi-perde', changeFrequency: 'weekly', priority: 0.95 },
  { path: '/urunler/mekanizmali-perdeler/jaluzi-perde/aluminyum-jaluzi-perde', changeFrequency: 'weekly', priority: 0.95 },
  { path: '/urunler/mekanizmali-perdeler/jaluzi-perde/ahsap-jaluzi-perde', changeFrequency: 'weekly', priority: 0.95 },
  { path: '/urunler/mekanizmali-perdeler/jaluzi-perde/deri-jaluzi-perde', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/urunler/mekanizmali-perdeler/stor-perde', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/urunler/mekanizmali-perdeler/stor-perde/screen-perde', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/urunler/mekanizmali-perdeler/stor-perde/tul-stor-perde', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/urunler/mekanizmali-perdeler/stor-perde/karartma-stor-perde', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/urunler/mekanizmali-perdeler/stor-perde/desenli-stor-perde', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/urunler/mekanizmali-perdeler/dikey-perde', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/urunler/mekanizmali-perdeler/zebra-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/mekanizmali-perdeler/cam-balkon-perdeleri', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/mekanizmali-perdeler/plise-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/mekanizmali-perdeler/bambu-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/mekanizmali-perdeler/silhouette-vision-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/tul-fon-perde', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/urunler/tul-fon-perde/modern-fon-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/tul-fon-perde/klasik-fon-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/tul-fon-perde/keten-fon-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/tul-fon-perde/kadife-fon-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/tul-fon-perde/desenli-fon-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/tul-fon-perde/tasarim-fon-perdeler', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/tul-fon-perde/keten-tul-perdeler', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/tul-fon-perde/baskili-fon-perdeler', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/dosemelik-kumas', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/urunler/dosemelik-kumas/dokulu-kumas', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/dosemelik-kumas/kadife-kumas', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/dosemelik-kumas/desenli-kumas', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/dosemelik-kumas/outdoor-kumas', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/dosemelik-kumas/deri-kumas', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/dosemelik-kumas/leopar-desenli-dosemelik-kumaslar', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/motorlu-perdeler', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/urunler/motorlu-tul-ve-kumas-perdeler', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/motorlu-perdeler/ahsap-jaluzi', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/motorlu-perdeler/motorlu-stor-perdeler', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/motorlu-perdeler/motorlu-dikey-perdeler', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/motorlu-perdeler/zip-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/motorlu-perdeler/dis-cephe-jaluzi', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/motorlu-perdeler/projeksiyon-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/urunler/perde-aksesuarlari', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/urunler/perde-aksesuarlari/rustik-takimlari', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/perde-aksesuarlari/kol-bagi', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/perde-aksesuarlari/bracol', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/metal-zincir-perde', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/urunler/metal-zincir-perde/metal-zincir-perde', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/metal-zincir-perde/metal-zincir-seperator', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/urunler/metal-zincir-perde/pro-collection', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/perde-modelleri', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/model-perdeler/klasik-ve-avangart-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/modern-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/rustikli-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/kruvaze-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/balon-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/katlamali-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/yuksek-tavanli-galeri-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/yuksek-tavanli-perde-modelleri', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/ip-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/cocuk-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/cibinlik-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/cati-kati-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/model-perdeler/kis-bahcesi-perde', changeFrequency: 'weekly', priority: 0.85 },
  { path: '/kurumsal-urunler', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/kurumsal-urunler/ozel-proje-perdeleri', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/kurumsal-urunler/cafe-restoran-perdeleri', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/kurumsal-urunler/hastane-perdeleri', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/kurumsal-urunler/ofis-perdeleri', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/kurumsal-urunler/otel-perdeleri', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/blog', changeFrequency: 'weekly', priority: 0.7 },
  { path: '/blog/dosemelik-kumas-ve-doseme-hizmetleri', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/dosemelik-kumaslar', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/buyuk-cam-ve-yuksek-tavanli-evler-icin-perde-secim-rehberi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/2026-avrupa-perde-trendler', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/perde-alirken-yapilan-10-buyuk-hata', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/kaliteli-stor-perde-nasil-anlasilir', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/salon-perde-secimi-nasil-yapilir', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/yuksek-tavanli-evlerde-ve-galeri-bosluklarinda-perde-secimi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/s-pile-perde-nedir', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/ahsap-jaluzi-perde-nedir-avantajlari-ve-kullanim-alanlari', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/sunscreen-stor-perde-nedir', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/yatak-odasinda-hangi-perde-kullanilmalidir', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/isik-gecirmeyen-perde-hangisidir', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/yeni-blog-yazisi', changeFrequency: 'weekly', priority: 0.5 },
  { path: '/blog/rustik-perde-modelleri-ve-kullanim-alanlari', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/mobilyaya-gore-perde-secimi-nasil-olmali', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/incek-veev-kis-bahcesi-motorlu-stor-perde-projesi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/avrupa-mahallesi-ahsap-jaluzi-perde-projesi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/meva-is-merkezi-kocamanlar-aluminyum-ofis-perde-projesi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/rinnova-incek-villa-perde-uygulamasi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/lotus-beytepe-art-deco-daire-perde-uygulamasi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/incek-uptown-konutlari-motorlu-stor-rustik-perde-projesi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/uptown-ankara-dubleks-villa-perde-projesi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/bilkent-bahce-konutlari-perde-uygulamasi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/koc-kuleleri-ankara-ofis-perde-uygulamasi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/incek-uptown-rustik-perde-motorlu-stor-perde-projesi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/alacaatli-ozel-villa-ipek-perde-ve-ozel-tasarim', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/mira-ofis-beytepe-motorlu-perde-sistemleri-projesi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/uskup-turk-buyukelciligi-rezidans-konutu-perde', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/alacaatli-pelit-cayyolu-villalari-perde-uygulamasi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/incek-veev-villa-somfy-motorlu-ahsap-jaluzi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/anadolu-tup-bebek-dikey-ve-hasta-bolucu-perde-projesi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/ani-metal-ankara-motorlu-ahsap-jaluzi-perde-projesi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/the-paragon-sogutozu-ankara-motorlu-sunscreen-perde', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/avend-voven-katlamali-perde-uygulamasi', changeFrequency: 'weekly', priority: 0.65 },
  { path: '/blog/cayyolu-angora-evleri-ahsap-jaluzi-keten-fon-perde', changeFrequency: 'weekly', priority: 0.65 },
]

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date()

  return sitemapEntries.map((entry) => ({
    url: entry.path === '/' ? baseUrl : `${baseUrl}${entry.path}`,
    lastModified,
    changeFrequency: entry.changeFrequency,
    priority: entry.priority,
  }))
}
