export interface BlogPost {
  id: number;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  date: string;
  image: string;
  readTime: string;
  href: string;
  slug: string;
}

export const blogPosts: BlogPost[] = [
  {
    "id": 22,
    "title": "Rustik Perde Sevenler Buraya",
    "excerpt": "Perde modelleri arasında oldukça önemli bir yere sahip olan zebralar esasında bir stor çeşididir. İşlevsel ve modern görünümleri...",
    "content": "<strong>Rustik Perde Sevenler Buraya</strong>\n\n<strong><img class=\"size-medium wp-image-21359 alignleft\" src=\"https://www.pileperde.com.tr/wp-content/uploads/2019/10/modern-rustik-modelleri-300x300.jpg\" alt=\"\" width=\"300\" height=\"300\" /></strong>Evleri tamamlayan perde seçimi dekorasyonda önemli yere sahiptir. Son dönemde özellikle genç evli çiftlerin tercihi rustik perde modelleridir. Bu modelleri tercih ederken özellikle mutfak alanlarında kullanılması gerektiği unutulmamalıdır. Mutfağın haricinde özellikle evin diğer alanlarında da tercih edilebilen bu perdeler evinize şık bir görünüm kazandırır. Özellikle odak noktasında kullanıldığında hoş bir görünüm elde edeceksiniz. Modern dokunuşlara sahip olan bu tasarımlar içinde birbirinden farklı model seçenekleri mevcuttur. Bu perde gruplarında model seçimi yaparken perde baskıları önemlidir. Nötr tonlara sahip olan perde seçenekleri evin iç ve doğal ışığın içeri girmesi açısından avantaj sağlamaktadır. Modern rustik tasarımlarla diğer mekanlar gibi işlek bir alan olan mutfak alanınız da fonksiyonellik kazanabilir.\n\n<strong>Modern Rustik Perde Trendleri</strong>\n\nModern rustik perde trendleri arasında farklı seçenekler yer almaktadır. Çeşitli marka ve şirketlerin geniş koleksiyonlarıyla beraber mutfaklarınız için dekorasyona en uygun perde seçeneklerini seçebilirsiniz. Modern rustik perde trendleri arasında keten benzeri dokuya sahip ürünler ve leke tutmaz modeller tercih edilebilir. Ayrıca odadaki diğer renklerle uyumlu nötr tonlara sahip ürünlerin de sıkça tercih edildiği bilinmektedir. Ayrıca bu model perdeler kendi içinde birçok özelliğe sahiptir. Güneş ışığını mükemmel bir şekilde geçiren perde modelleri gün içinde evinizin daha aydınlık gözükmesine yardımcı olmaktadır.\n\n<strong>Rustik Perde Seçerken Dikkat Edilmesi Gerekenler</strong>\n\nMutfağın geneline uyum sağlayacak renk seçimi yapın. Birbirini tamamlayan renklerle ortaya çıkan renk uyumu, ortama huzur katıyor. Mutfak dekorasyonunuzu perde seçiminizle daha iddialı hale getirebilirsiniz. Ayrıca mutfağın aldığı güneş ışığına ve mevsimlere göre dikkatli bir seçim yapmayı unutmayın. Yaz aylarında daha açık tonlarda tercihler yaparken kış aylarında koyu tonlar kullanabilirsiniz.\n<h4 style=\"text-align: center;\"><a href=\"https://www.pileperde.com.tr/model-perdeler/rustikli-perde/\">Rustikli Perde Modellerimiz için tıklayınız...</a></h4>",
    "category": "Perde Bilgisi",
    "date": "27 Aralık 2020",
    "image": "/api/public/media/images/e672f06a-0f78-4437-a831-0a401c10c82a/file",
    "readTime": "1 dk okuma",
    "href": "/blog/rustik-perde-sevenler-buraya",
    "slug": "rustik-perde-sevenler-buraya"
  },
  {
    "id": 21,
    "title": "Zebra Perdeler Nasıl Temizlenir?",
    "excerpt": "Perde modelleri arasında oldukça önemli bir yere sahip olan zebralar esasında bir stor çeşididir. İşlevsel ve modern görünümleri...",
    "content": "<strong>Zebra Perdeler Nasıl Temizlenir?</strong>\n\n<strong><img class=\"size-medium wp-image-21381 alignleft\" src=\"/api/public/media/images/d77b3bf2-4b30-43d4-b0fc-dc7b8bf70adf/file\" alt=\"Zebra Perde\" width=\"300\" height=\"300\" /></strong>Perde modelleri arasında oldukça önemli bir yere sahip olan zebralar esasında bir stor çeşididir. İşlevsel ve modern görünümleriyle günlük yaşamda zebra perde temizliği rahatlıkla yapılabilmektedir. Esasında yatay jaluziler gibi çok etkili perdelerde birbirini takip eden desenlerden dolayı pek çok isimle anılır. Yatay olarak sıralanmış birbirini takip eden şeffaf ve yarı geçirgen perdeler, kaydırılarak görünümü ve ışık geçirgenliğini kontrol etmeye imkân tanır. Dekorasyon alanında çok başarılı görünümlere sahip olan perdeler, estetik açıdan çok modern görünümleriyle aslında ışık kontrollerinin yanında mahremiyet sağlamak amacıyla da kullanılmaktadır.\n\n<strong>Zebra Perde Bakımı Nasıl Olmalı?</strong>\n\nZebra perdeler renk seçeneklerine bağlı olarak leke ve kirlere karşı oldukça hassastır. Zamanla kirlenmesini önlemek için zebra perde temizliği büyük bir hassasiyet gösterilmeli ve uygun periyotlarda yapılmalıdır. Diğer önemli olan konu ise perdelerinizin çok fazla yıpranıp ömrünü kısaltmamak için perde temizliğine ve bakımına önem vermenizdir. Zebra perdenizi temizlemeden önce üzerindeki toz ve kirlerden kurtarmak için yumuşak bir fırça veya elektrik süpürgesi kullanabilirsiniz. Toz ve kirlerden arındırılan perdeleri daha kolay bir şekilde temizlemeniz mümkün hale gelir. Perdelerinizi nemli bir bez yardımıyla silerek temizleyebilirsiniz. Bu sayede perdenizin ömrünü uzatarak daha hijyenik bir ortama sahip olabilirsiniz. Ayrıca bu işlemleri kendi başınıza yapmak istemiyorsanız uzmanları arayarak zebra perde temizliği işlemini gerçekleştirebilirsiniz.\n\n<strong>Zebra Perdeler Hangi Alanlarda Kullanılır?</strong>\n\nBirbirinden farklı model ve renk seçeneğine sahip olan zebra perdeler kolay temizlenmeleri ve modern görünümleri sayesinde evlerde ve işyerlerinde sıkça tercih edilir. Evlerde mutfak, çocuk odası ve banyo alanlarında sıklıkla kullanılmaktadır. Ayrıca işyerlerinde, hastanelerde ve diğer kamu kuruluşlarında da yaygın olarak tercih edilmektedir. Zebra perdeler stor perdelerden farklı olarak kapalıyken de fazla yer kaplamazlar. Bu özelliği sayesinde özellikle küçük alanlarda daha sık kullanılmaktadır. Birbirinden özel tasarım seçeneklerine sahip olan zebra perdeler sayesinde hayalinizdeki mekâna sahip olabilirsiniz.\n<h4 style=\"text-align: center;\"><a href=\"https://www.pileperde.com.tr/stor-perdeler/stor-zebra/\">Zebra Perde Modellerimiz için tıklayınız...</a></h4>",
    "category": "Bakım",
    "date": "19 Aralık 2020",
    "image": "/api/public/media/images/d77b3bf2-4b30-43d4-b0fc-dc7b8bf70adf/file",
    "readTime": "1 dk okuma",
    "href": "/blog/zebra-perdeler-nasil-temizlenir",
    "slug": "zebra-perdeler-nasil-temizlenir"
  },
  {
    "id": 20,
    "title": "Çocuk Odalarında Perde Seçiminde Nelere Dikkat Edilmelidir?",
    "excerpt": "Mutfaklar, evin en çok vakit geçirilen bölümleridir. Bu alanlarda tercih edilecek perdelerin estetik olduğu kadar işlevsel olmasına...",
    "content": "<strong>Çocuk Odalarında Perde Seçiminde Nelere Dikkat Edilmelidir?</strong>\n\n<strong><img class=\"size-medium wp-image-21426 alignleft\" src=\"/api/public/media/images/15eb9838-e405-4214-824f-13829bab07f3/file\" alt=\"Çocuk Odası Perde\" width=\"300\" height=\"300\" /></strong>Doğanın sıcak etkisi özellikle evimizin bazı bölümlerinde oldukça yoğun olarak hissedilir. Yön olarak güneş gören bölümlerde doğrudan güneş ışığına maruz kalınır ve mevsime göre sıcaklıkları da dikkate aldığımızda oda içerisinde çok yüksek sıcaklıklarla karşı karşıya kalmak durumunda kalabiliriz. Özellikle çocuk odası tercih ettiğimiz bu perde sayesinde güneşin zararlı ışınlarından korunmak için karartma özelliğine sahip modeller tercih edilmelidir.\n\nÇocuk odası için günün tüm saatlerinde kullanılacak olan perde seçimlerine baktığınızda ilk dikkat etmemiz gereken husus güneşin zararlı ışınlarından ne kadar korunma sağladığıdır. Mevsimine göre değişkenlik gösterebilecek olan sıcaklık ve güneş ışığı etkisi perde seçimi sayesinde çok daha kaliteli hale getirilebilmektedir. Çocuk odası için günün tüm saatlerinde koruma sağlamak adına fon perde modelleri de özellikle tercih edilebilir.\n\n<strong>Çocuk Odası İçin Perde</strong>\n\nÇocuklarının odasında perde seçimi yapmak isteyen ebeveynler için tavsiyeler vermek gerekirse, güneşin zararlı ışıklarından koruyan perdeler sayesinde hem güneşi hem de günün ışığını kaliteli hale getirmek söz konusu olabilmektedir. Perde seçimi yapmak adına önemli olan diğer bir unsur ise perde üzerine baskı yapılmasıdır. Çocuklarınızın yaşına göre değişkenlik gösterebilecek olan bu tasarımlar sayesinde çocuğunuzu odasında çok daha mutlu hissedebilecek sevimli karakterler ve şekiller perdelerde bulunmaktadır.\n\nÇocuk odası için yatağının bulunduğu konuma göre perde seçimi yapmak gerekir. Yatağına gelen güneş ışınlarını engellemeyen perdeler çocuklarınızın sağlığı açısından risk oluşturacaktır. Güneşin zararlı ışınlarından koruma açısından çocuk odası perdeleri büyük bir önem teşkil etmektedir. Odasını sevmeyen ve odasında zaman geçirmek istemeyen çocuklara daha renkli ve çocuğunuzu tanıyan ebeveynler tarafından perde seçimi ile çok daha sevimli bir oda dekore edilebilir. Çocuklarınızın odasını ön plana çıkaracak ürünlerden bir tanesi olan perde modeli seçimi oldukça önemlidir. Fiyatlar oldukça uygundur ve çocuk odası perde modelleri sayesinde rengarenk odalara sahip olabilirsiniz.\n<h4 style=\"text-align: center;\"><a href=\"https://www.pileperde.com.tr/model-perdeler/cocuk-perde/\">Çocuk Odası Perde Modellerimiz için tıklayınız...</a></h4>",
    "category": "Çocuk Odası",
    "date": "11 Aralık 2020",
    "image": "/api/public/media/images/15eb9838-e405-4214-824f-13829bab07f3/file",
    "readTime": "2 dk okuma",
    "href": "/blog/cocuk-odalarinda-perde-seciminde-nelere-dikkat-edilmelidir",
    "slug": "cocuk-odalarinda-perde-seciminde-nelere-dikkat-edilmelidir"
  },
  {
    "id": 19,
    "title": "Mutfaklar İçin Tercih Edilebilecek Perdeler",
    "excerpt": "Mutfaklar, evin en çok vakit geçirilen bölümleridir. Bu alanlarda tercih edilecek perdelerin estetik olduğu kadar işlevsel olmasına...",
    "content": "<strong>Mutfaklar İçin Tercih Edilebilecek Perdeler</strong>\n\n<img class=\"size-medium wp-image-21354 alignleft\" src=\"/api/public/media/images/65400517-fb3a-43e0-9e40-15572df5beef/file\" alt=\"Drape Tül Perdeler\" width=\"300\" height=\"300\" />Mutfaklar, evin en çok vakit geçirilen bölümleridir. Bu alanlarda tercih edilecek perdelerin estetik olduğu kadar işlevsel olmasına da özen gösterilmelidir. Piyasada çeşitli <strong>mutfak perdeleri</strong> modelleri bulunmaktadır.\n\n<strong>Rustik Perde Modelleri</strong>\n\n<strong>Mutfak perdeleri </strong>modelleri içerisinde dikkat çeken rustik perdeler Türkçe kelime anlamıyla \"kırsal ve doğal\" demektir. Bu model perdelerin genelinde doğal renkler ön plandadır. Doğadan gelen renkler, mutfaklarınıza da ayrı bir hava katmaktadır. Kıvrımların ön plana çıktığı bu perde modellerinde, aksesuarla beraber satışı yapılan ürünler mevcuttur. Bu aksesuarlar, oyuncak ayıcıklar, çiçekler ve kalplerdir. Bu model perdelerin kullanımı modern mutfaklara ayrı bir görüntü sağlamaktadır.\n\n<strong>Stor Perde Modelleri</strong>\n\nFonksiyonel ve şık bir görünümü olan bu perde modelleri, cam önlerinde hem ışık hem de görüntü kontrolünün sağlanması hususunda kullanılmaktadır. Bu perde modellerinde çok fazla renk seçeneği bulunmakta ve pencere önündeki alan fazla yer kaplamadan kendi mekanizması aracılığı ile açılıp kapatılabilmektedir. <strong>Mutfak perdelerinizle</strong> aynı renkte stor perdeler tercih ederek alanları daha gösterişli hale getirebilirsiniz. Bu ürünler kolay temizlenen özelliğe sahiptir. Alanları küçük olan mutfaklara daha fazla alan sağlamak adına stor perde modelleri tercih edilebilir.\n\n<strong>Jaluzi Modelleri</strong>\n\nGenellikle ofislerde tercih edilen bu model perdeler ahşap ve alüminyum olarak ikiye ayrılır. Pratik kullanımları sayesinde tercih sebebi olan bu perde modelleri güneş ışınlarını engellemek ve gizlilik sağlamak adına kullanıcılara imkan sunmaktadır. Mutfak pencerelerinde de kullanılan ahşap jaluziler, doğal bir görüntü sağlamakta ve kaliteli malzemeler kullanıldığından yıllarca dayanabilmektedir. Ayrıca bu perde modelleri birbirinden farklı renk seçenekleri ile mutfaklarınıza uyum sağlamaktadır.\n\n<strong>Drape Perde Modelleri</strong>\n\nBu model perdeler çok az ışık alan mutfaklar için uygundur ve ışık geçirgenliği çok yüksektir. Polyester ya da ketenden yapılan bu ürünler parlaklık özelliği sayesinde her zaman yeni gibi görünmektedir. Birbirinden farklı renk ve doku seçeneği mutfaklar için tercih sebebi olmaktadır.\n<h4 style=\"text-align: center;\"><a href=\"https://www.pileperde.com.tr/mutfak-perdesi/\">Mutfak Perdeleri Modellerimiz için tıklayınız...</a></h4>",
    "category": "Mutfak",
    "date": "9 Aralık 2020",
    "image": "/api/public/media/images/65400517-fb3a-43e0-9e40-15572df5beef/file",
    "readTime": "2 dk okuma",
    "href": "/blog/mutfaklar-icin-tercih-edilebilecek-perdeler",
    "slug": "mutfaklar-icin-tercih-edilebilecek-perdeler"
  },
  {
    "id": 18,
    "title": "Mobilyaya Göre Perde Seçimi Nasıl Olmalı?",
    "excerpt": "İç mekanların en önemli aksesuarları arasında bulunan perdelerin seçimi yaşam alanlarının görüntüsünü bir anda değiştirebilir...",
    "content": "<strong>Mobilyaya Göre Perde Seçimi Nasıl Olmalı?</strong>\n\n<strong><img class=\"size-medium wp-image-21375 alignleft\" src=\"https://www.pileperde.com.tr/wp-content/uploads/2019/10/motorlu-perde-ankara1-300x300.jpg\" alt=\"\" width=\"300\" height=\"300\" /></strong>İç mekanların en önemli aksesuarları arasında bulunan perdelerin seçimi yaşam alanlarının görüntüsünü bir anda değiştirebilir. Bu yüzden <strong>mobilyaya göre perde seçimi</strong>, önem arz eden konuların başında gelmektedir. Evimiz ya da iş yerimizin modern ve şık görünmesi için perde seçimi hayati önem taşımaktadır.\n\nMobilyalarınıza göre perde seçimi yapmadan önce dikkat etmeniz gereken bazı konular bulunmaktadır. İç mekânlarınızın duvar rengiyle uyumlu, kullanılan eşyalarla aynı tonlarda ve her şeyden önce zevkinize hitap eden perdeler seçmeniz tavsiye edilir. Bilinçsiz olarak yapılan perde seçimleri beraberinde göz yorgunluğu ve gerginlik sağlayabilmektedir.\n\n<strong>Perde Kumaş Seçiminde Dikkat Edilmesi Gerekenler</strong>\n\nPerde seçimi yaparken en ince ayrıntılara bile dikkat etmeniz gerekir. Mobilyalarınıza uygun perde seçtikten sonra kumaş seçimi de büyük önem taşımaktadır. Ayrıca seçilecek olan perde kumaşı, güneş alan odanızın sıcaklığına karşı dayanıklı olmalıdır. Yazın serin, kışın ise sıcak tutan kumaşlar seçmeniz avantaj sağlayacaktır. Ayrıca kumaş seçimi yaparken işlevselliğin yanında hijyen ve temizlik açısından da özelliklerine dikkat etmeniz gerekmektedir.\n\nGenellikle perde kumaşlarının kendi başlarına çok zarif ve muazzam desenleri olduğu bilinir. Fakat <strong>mobilyaya göre perde seçimi</strong> yaparken kumaşın yumuşaklığı, deseni ve görüntüsünün yanında mobilyalarınızı da ön plana çıkaracak parçalar seçmeniz gerekmektedir.\n\n<strong>Salon ve Yatak Odası Perdeleri</strong>\n\nSalonunuz için perde seçerken her iki pencerenizin de aynı görünmesine dikkat edin. Perde modelinizin bütün mobilyalarınıza uygun olması ve aynı görünmesi odanızın daha zarif görünmesi açısından önem taşımaktadır. Ayrıca eğer salonunuz geniş bir mekâna sahipse ince tül modelleri sizin için daha kullanışlı olacaktır.\n\nYatak odası için kullanabileceğiniz en ideal perdeler güneş ışığını geçirmeyen fon perdeler olacaktır. Ayrıca renk seçimi yaparken beyaz ya da açık tonlar seçmeniz mekanı daha geniş gösterecektir.\n<h4 style=\"text-align: center;\"><a href=\"https://www.pileperde.com.tr/perde-cesitleri/\">Perde Çeşitlerimizi Görmek için tıklayınız...</a></h4>",
    "category": "Perde Bilgisi",
    "date": "24 Kasım 2020",
    "image": "/api/public/media/images/e99d36d6-2dde-4abd-9900-bbe917248bc7/file",
    "readTime": "2 dk okuma",
    "href": "/blog/mobilyaya-gore-perde-secimi-nasil-olmali",
    "slug": "mobilyaya-gore-perde-secimi-nasil-olmali"
  }
];