import { permanentRedirect } from 'next/navigation'

type Params = { slug?: string[] }

const legacyEnglishRedirects: Record<string, string> = {
  '': '/',
  about: '/hakkimizda',
  contact: '/iletisim',
  products: '/urunler',
  'products/blinds-and-shades': '/urunler/mekanizmali-perdeler',
  'products/sheer-and-drapery': '/urunler/tul-fon-perde',
  'products/upholstery-fabrics': '/urunler/dosemelik-kumas',
  'products/motorised-window-treatments': '/urunler/motorlu-perdeler',
  'products/curtain-accessories': '/urunler/perde-aksesuarlari',
  'products/metal-chain-curtains': '/urunler/metal-zincir-perde',
  'products/blinds/venetian-blinds': '/urunler/mekanizmali-perdeler/jaluzi-perde',
  'products/blinds/venetian-blinds/aluminium': '/urunler/mekanizmali-perdeler/jaluzi-perde/aluminyum-jaluzi-perde',
  'products/blinds/venetian-blinds/wooden': '/urunler/mekanizmali-perdeler/jaluzi-perde/ahsap-jaluzi-perde',
  'products/blinds/venetian-blinds/leather': '/urunler/mekanizmali-perdeler/jaluzi-perde/deri-jaluzi-perde',
  'products/blinds/roller-blinds': '/urunler/mekanizmali-perdeler/stor-perde',
  'products/blinds/roller-blinds/sunscreen': '/urunler/mekanizmali-perdeler/stor-perde/screen-perde',
  'products/blinds/roller-blinds/sheer': '/urunler/mekanizmali-perdeler/stor-perde/tul-stor-perde',
  'products/blinds/roller-blinds/blackout': '/urunler/mekanizmali-perdeler/stor-perde/karartma-stor-perde',
  'products/blinds/roller-blinds/patterned': '/urunler/mekanizmali-perdeler/stor-perde/desenli-stor-perde',
  'products/blinds/vertical-blinds': '/urunler/mekanizmali-perdeler/dikey-perde',
  'products/blinds/zebra-blinds': '/urunler/mekanizmali-perdeler/zebra-perde',
  'products/blinds/balcony-glazing-blinds': '/urunler/mekanizmali-perdeler/cam-balkon-perdeleri',
  'products/blinds/pleated-blinds': '/urunler/mekanizmali-perdeler/plise-perde',
  'products/blinds/bamboo-blinds': '/urunler/mekanizmali-perdeler/bambu-perde',
  'products/blinds/silhouette-vision-blinds': '/urunler/mekanizmali-perdeler/silhouette-vision-perde',
  'products/curtains/modern-decorative-curtains': '/urunler/tul-fon-perde/modern-fon-perde',
  'products/curtains/classic-decorative-curtains': '/urunler/tul-fon-perde/klasik-fon-perde',
  'products/curtains/linen-curtains': '/urunler/tul-fon-perde/keten-fon-perde',
  'products/curtains/velvet-curtains': '/urunler/tul-fon-perde/kadife-fon-perde',
  'products/curtains/patterned-curtains': '/urunler/tul-fon-perde/desenli-fon-perde',
  'products/curtains/designer-curtains': '/urunler/tul-fon-perde/tasarim-fon-perdeler',
  'products/curtains/linen-sheers': '/urunler/tul-fon-perde/keten-tul-perdeler',
  'products/curtains/printed-curtains': '/urunler/tul-fon-perde/baskili-fon-perdeler',
  'products/upholstery-fabrics/textured': '/urunler/dosemelik-kumas/dokulu-kumas',
  'products/upholstery-fabrics/velvet': '/urunler/dosemelik-kumas/kadife-kumas',
  'products/upholstery-fabrics/patterned': '/urunler/dosemelik-kumas/desenli-kumas',
  'products/upholstery-fabrics/outdoor': '/urunler/dosemelik-kumas/outdoor-kumas',
  'products/upholstery-fabrics/leather': '/urunler/dosemelik-kumas/deri-kumas',
  'products/upholstery-fabrics/leopard-print': '/urunler/dosemelik-kumas/leopar-desenli-dosemelik-kumaslar',
  'products/motorised-window-treatments/motorised-curtains': '/urunler/motorlu-tul-ve-kumas-perdeler',
  'products/motorised-window-treatments/wooden-venetian-blinds': '/urunler/motorlu-perdeler/ahsap-jaluzi',
  'products/motorised-window-treatments/roller-blinds': '/urunler/motorlu-perdeler/motorlu-stor-perdeler',
  'products/motorised-window-treatments/vertical-blinds': '/urunler/motorlu-perdeler/motorlu-dikey-perdeler',
  'products/motorised-window-treatments/zip-screens': '/urunler/motorlu-perdeler/zip-perde',
  'products/motorised-window-treatments/external-venetian-blinds': '/urunler/motorlu-perdeler/dis-cephe-jaluzi',
  'products/motorised-window-treatments/projection-screens': '/urunler/motorlu-perdeler/projeksiyon-perde',
  'products/curtain-accessories/curtain-poles': '/urunler/perde-aksesuarlari/rustik-takimlari',
  'products/curtain-accessories/tiebacks': '/urunler/perde-aksesuarlari/kol-bagi',
  'products/curtain-accessories/holdbacks': '/urunler/perde-aksesuarlari/bracol',
  'products/metal-chain-curtains/room-dividers': '/urunler/metal-zincir-perde/metal-zincir-seperator',
  'products/metal-chain-curtains/pro-collection': '/urunler/metal-zincir-perde/pro-collection',
  'curtain-designs': '/perde-modelleri',
  'curtain-designs/classic-and-ornate': '/model-perdeler/klasik-ve-avangart-perde',
  'curtain-designs/contemporary': '/model-perdeler/modern-perde',
  'curtain-designs/curtain-pole': '/model-perdeler/rustikli-perde',
  'curtain-designs/cross-over': '/model-perdeler/kruvaze-perde',
  'curtain-designs/balloon': '/model-perdeler/balon-perde',
  'curtain-designs/roman-blinds': '/model-perdeler/katlamali-perde',
  'curtain-designs/double-height-spaces': '/model-perdeler/yuksek-tavanli-galeri-perde',
  'curtain-designs/string-curtains': '/model-perdeler/ip-perde',
  'curtain-designs/children-rooms': '/model-perdeler/cocuk-perde',
  'curtain-designs/canopy-curtains': '/model-perdeler/cibinlik-perde',
  'curtain-designs/loft-windows': '/model-perdeler/cati-kati-perde',
  'curtain-designs/conservatories': '/model-perdeler/kis-bahcesi-perde',
  commercial: '/kurumsal-urunler',
  'commercial/bespoke-projects': '/kurumsal-urunler/ozel-proje-perdeleri',
  'commercial/restaurants-and-cafes': '/kurumsal-urunler/cafe-restoran-perdeleri',
  'commercial/healthcare': '/kurumsal-urunler/hastane-perdeleri',
  'commercial/offices': '/kurumsal-urunler/ofis-perdeleri',
  'commercial/hotels': '/kurumsal-urunler/otel-perdeleri',
  corporate: '/kurumsal',
  faq: '/sss',
  journal: '/blog',
  blog: '/blog',
  'privacy-policy': '/gizlilik-politikasi',
  'terms-of-use': '/kullanim-kosullari',
  'blog/wooden-venetian-blinds-guide': '/blog/ahsap-jaluzi-perde-nedir-avantajlari-ve-kullanim-alanlari',
  'blog/motorised-window-treatments-guide': '/blog/motorlu-ve-elektrikli-perde-sistemleri',
  'blog/how-to-choose-living-room-curtains': '/blog/salon-perde-secimi-nasil-yapilir',
}

export default async function LegacyEnglishRoute({ params }: { params: Promise<Params> }) {
  const { slug = [] } = await params
  permanentRedirect(legacyEnglishRedirects[slug.join('/')] || '/')
}
